### ISSUE TITLE
签名服务异常

### ISSUE THREAD

**Issue by pilgrim773** [touchscale/Qsign#3]
今天早上bot不响应了，重新启动双方后KFCFactory提示qsign服务异常，切到签名这边看输出，未发现error，再次尝试重启双方程序，问题依旧
![Screenshot_2023-11-30-15-27-27-792_com sonelli juicessh](https://github.com/touchscale/Qsign/assets/13644483/588d6a19-cd38-4ed9-9e23-d3dc547dc4b2)

使用版本1.1.9b4

**Comment by touchscale** [comment]
看看喵崽的api日志

**Comment by pilgrim773** [comment]
更换txlib到8.9.88版本后已经可以使用了。不清楚说的是哪个api？

虽然没有这个问题了，不过还是在一天内多次自动关闭服务，准备用onebot了……

**Comment by touchscale** [comment]
建议用NTQQ，签名15天一封不划算
