### ISSUE TITLE
error: sign_tail_manager.h:147 tryRequestTail

### ISSUE THREAD

**Issue by zwa73** [touchscale/Qsign#4]
在直接 bin/unidbg-fetch-qsign --basePath=txlib/8.9.90 启动时，bot发送消息时出现以下信息是否正常？
我使用的是go-cq v1.2.0
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 11
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 15
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 17
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 27

**Comment by touchscale** [comment]
高QQ协议版本是这样的

**Comment by Akesaka-Hitsuki** [comment]
环境：ubuntu 20.04
版本：直接git clone的库
调用方式：sudo bash bin/unidbg-fetch-qsign --basePath=txlib/8.9.88

用的mirai 2.16.0和fix-protocol-version 1.13.0
在出现以下报错后 这边就和mirai那边断连了 事实上这不是第一次出现这个问题了
```
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 15
Dec 11, 2023 1:02:51 PM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /data/app/~~vbcRLwPxS0GyVfqT-nCYrQ==/com.tencent.mobileqq-xJKJPVp9lorkCgR_w5zhyA==/lib/arm64
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 3946
[FEKit_]error: o3_channel_encrypt.h:495 ecdh repeat establish
FEBound.transform(93ec3e53522043b2005fa4d7c4e60195575c4f9ce98f2a0da42a675f400d68de) => fbd8900b19f72a894052036e3728523d8838e1e5882cd2cabbbe5ce0f0df3ea1
[FEKit_]error: o3_channel_encrypt.h:547 est check: 554420009bf62ce9c6da81e2505c5d34410e80bf7f4c94e141e55c4a1b5b16e353cb906c73b1bcfac6042028d11137b9
[FEKit_]error: ChannelManager.cpp:97 o3cm@S: O3GetTail, trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
```
