### ISSUE TITLE
使用最新的9.0.8qsign依然code45

### ISSUE THREAD

**Issue by xanthichi** [touchscale/Qsign#6]
9.0.8版本在滑块验证部分闪退
![image](https://github.com/touchscale/Qsign/assets/135406843/8cb5c259-910c-4696-b181-c6253cb74d04)
8.9.80版本爆code45（其他8.9.x版本一样）
![image](https://github.com/touchscale/Qsign/assets/135406843/9c86d779-3285-4429-b5a5-1612d645bbfe)
↓（我不确定是否和图中画框区有关系，如果有，请问该如何调整）
![image](https://github.com/touchscale/Qsign/assets/135406843/19a9cf02-77e8-4971-8d4e-3bbc2c0ccb20)

**Comment by touchscale** [comment]
可以尝试以管理员权限运行终端

**Comment by xanthichi** [comment]
> 可以尝试以管理员权限运行终端
 我就是在Linux的root用户下运行的qsign

**Comment by kissnavel** [comment]
> > 可以尝试以管理员权限运行终端
> > 我就是在Linux的root用户下运行的qsign

1、9.0.0及以上版本因采用新架构，使用时会报错内存错误等其他错误并强制退出，暂无有效解决办法
2、linux上8.9.80仍然会报code45，推荐用8.9.78，或者高于8.9.80并配置崩溃自动重启，也可以使用docker来配置并设置cron参数定时重启容器

**Comment by touchscale** [comment]
[解决喵崽的QSignApi自动崩溃问题的linux脚本](https://gitee.com/touchscale/Qsign/issues/I8GLZN#note_24063898_link)
